### ISSUE TITLE
Wrong manifest path in services/ElixirService.php

### ISSUE THREAD

**Issue by juliencharette** [venveo/craft-elixir#8]
The following
```
$this->manifest = CRAFT_BASE_PATH . $this->publicPath [...]
```
should be
```
$this->manifest = dirname(CRAFT_BASE_PATH) . '/' . $this->publicPath [...]
```
or something like
```
craft()->config->get('environmentVariables')['basePath']
```
As per [craft docs](https://craftcms.com/docs/php-constants#craft-base-path):

Craft uses CRAFT_BASE_PATH as the starting point for **finding all of the folders traditionally located in craft/**. So basically the plugin tries to read the manifest under `./craft/public/build/...` but will never find it there, it's generated by elixir under `./public/build/...`.

**Comment by sweetroll** [comment]
+1

I got mine working with the first suggestion:

`$this->manifest = dirname(CRAFT_BASE_PATH) . '/' . $this->publicPath [...]`
